### ISSUE TITLE
Add feature lens for pnpm workspace protocol & rename this vscode extension as pnpm lens

### ISSUE THREAD

**Issue by manudeli** [antfu/vscode-pnpm-catalog-lens#1]
### Clear and concise description of the problem

In my opinion, "workspace:*" could be replaced like "catalog:"

<img width="409" alt="image" src="https://github.com/user-attachments/assets/f8562ecf-d20e-45e0-bc17-56060c070f7f">

### Suggested solution

Same feature with catalog lens..!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I thought about that - but is it really worth it? Supposely `workspace:*` should always point to the same version, where you don't actually care. Also, it would be a lot of extra work to read the version of each workspace package. For now, let's considere this is a no-goal, feel free to fork it and do another extension if you really want it. Thanks.
